source "qemu" "vm" {
  accelerator      = var.qemu_accelerator
  boot_command     = var.boot_command
  boot_wait        = local.boot_wait
  cd_files         = local.cd_files
  cpus             = var.cpus
  communicator     = local.communicator
  disk_size        = var.disk_size
  display          = var.headless ? "none" : var.qemu_display
  floppy_files     = local.floppy_files
  headless         = var.headless
  http_directory   = local.http_directory
  iso_checksum     = var.iso_checksum
  iso_url          = var.iso_url
  machine_type     = local.qemu_machine_type
  memory           = local.memory
  output_directory = "${local.output_directory}-qemu"
  qemu_binary      = local.qemu_binary
  qemuargs         = local.qemuargs
  shutdown_command = local.shutdown_command
  shutdown_timeout = var.shutdown_timeout
  ssh_password     = var.ssh_password
  ssh_port         = var.ssh_port
  ssh_timeout      = var.ssh_timeout
  ssh_username     = var.ssh_username
  winrm_password   = var.winrm_password
  winrm_timeout    = var.winrm_timeout
  winrm_username   = var.winrm_username
  vm_name          = local.vm_name
}