# CMake generated Testfile for 
# Source directory: /home/scaldwell/git/monorepo
# Build directory: /home/scaldwell/git/monorepo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[AnsiColorsTest]=] "/home/scaldwell/git/monorepo/build/AnsiColors/AnsiColors_test")
set_tests_properties([=[AnsiColorsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[ChannelTest]=] "/home/scaldwell/git/monorepo/build/Channel/Channel_test")
set_tests_properties([=[ChannelTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[yamlTest]=] "/home/scaldwell/git/monorepo/build/yaml/yaml_test")
set_tests_properties([=[yamlTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[SimpleLockTest]=] "/home/scaldwell/git/monorepo/build/SimpleLock/SimpleLock_test")
set_tests_properties([=[SimpleLockTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[SmartPointerTest]=] "/home/scaldwell/git/monorepo/build/SmartPointer/SmartPointer_test")
set_tests_properties([=[SmartPointerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[ValidatorsTest]=] "/home/scaldwell/git/monorepo/build/Validators/Validators_test")
set_tests_properties([=[ValidatorsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[exceptionsTest]=] "/home/scaldwell/git/monorepo/build/exceptions/exceptions_test")
set_tests_properties([=[exceptionsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[flagsTest]=] "/home/scaldwell/git/monorepo/build/flags/flags_test")
set_tests_properties([=[flagsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[formatterTest]=] "/home/scaldwell/git/monorepo/build/formatter/formatter_test")
set_tests_properties([=[formatterTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[CommonTest]=] "/home/scaldwell/git/monorepo/build/Common/Common_test")
set_tests_properties([=[CommonTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[LogServerTest]=] "/home/scaldwell/git/monorepo/build/LogServer/LogServer_test")
set_tests_properties([=[LogServerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[LoggerTest]=] "/home/scaldwell/git/monorepo/build/Logger/Logger_test")
set_tests_properties([=[LoggerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[TcpClientTest]=] "/home/scaldwell/git/monorepo/build/TcpClient/TcpClient_test")
set_tests_properties([=[TcpClientTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[TcpCommonTest]=] "/home/scaldwell/git/monorepo/build/TcpCommon/TcpCommon_test")
set_tests_properties([=[TcpCommonTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[TcpServerTest]=] "/home/scaldwell/git/monorepo/build/TcpServer/TcpServer_test")
set_tests_properties([=[TcpServerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[typesTest]=] "/home/scaldwell/git/monorepo/build/types/types_test")
set_tests_properties([=[typesTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
add_test([=[helloworldTest]=] "/home/scaldwell/git/monorepo/build/helloworld/helloworld_test")
set_tests_properties([=[helloworldTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/scaldwell/git/monorepo/CMake/cpp_add_projects.cmake;38;add_test;/home/scaldwell/git/monorepo/CMakeLists.txt;41;cpp_add_projects;/home/scaldwell/git/monorepo/CMakeLists.txt;0;")
