#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
printf "\033[34m>starting %s\033[0m" "$0"

make security || {
  printf "\033[31m>Lint/security check failed %s\033[0m" "$0"
  exit 1
}

printf "\033[32m>Linter/Security check: ok %s\033[0m" "$0"

printf "\033[32m>ok %s\033[0m" "$0"

