#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
echo "\033[34m>starting $0\033[0m"

make security || {
  echo "\033[31m>Lint/security check failed $0\033[0m"
  exit 1
}

echo "\033[32m>Linter/Security check: ok $0\033[0m"

echo "\033[32m>ok $0\033[0m"

