package words

const (
	Build      = "build"
	Check      = "check"
	Command    = "command"
	Config     = "config"
	Create     = "create"
	Cri        = "cri"
	Delete     = "delete"
	Exec       = "exec"
	FileName   = "filename"
	Free       = "free"
	Group      = "group"
	Help       = "help"
	Host       = "host"
	Hypervisor = "hypervisor"
	Language   = "language"
	Lint       = "lint"
	List       = "list"
	Parameters = "parameters"
	Permission = "permission"
	Platform   = "platform"
	Project    = "project"
	RateLimit  = "ratelimit"
	Show       = "show"
	Test       = "test"
)
