package JiraIssue

/*
{
  "fields": {
    "project": {
      "key": "{{jira_project}}"
    },
    "summary": "Creating From Collection",
    "description": {
      "type": "doc",
      "version": 1,
      "content": [
        {
          "type": "paragraph",
          "content": [
            {
              "type": "text",
              "text": "This is an autogenerated issue from a demo."
            }
          ]
        }
      ]
    },
    "issuetype": {
      "name": "Task"
    }
  }
}
*/

// Issue - JSON descriptor for a JIRA issue
type Issue struct {
    Fields struct {
        Project struct {
            Key string `json:"key"`
        } `json:"project"`
        Summary     string `json:"summary"`
        Description string `json:"description"`
        Issuetype   struct {
            Name string `json:"name"`
        } `json:"issuetype"`
    } `json:"fields"`
}
