---
name: main-branch

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'darwin'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: go mod tidy
        shell: bash
        run: go mod tidy

      - name: install staticcheck
        shell: bash
        run: |
          export STATICCHECK_CACHE="${{ runner.temp }}/staticcheck"
          go get -u honnef.co/go/tools
          go get honnef.co/go/tools/cmd/staticcheck
          go install "honnef.co/go/tools/cmd/staticcheck@2023.1.3"
          echo "Verify install..."
          command -v staticcheck || {
            echo 'install failed.'
            exit 1
          }

      - name: Run linter ${{ matrix.go-version }}
        shell: bash
        run: |
          PATH=$(go env GOPATH):${PATH} make lint

      - name: Setup Git
        shell: bash
        run: |
          git config --local user.email "github@samcaldwell.net"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: Generate Badge
        id: badge
        run: |
          #BRANCH="update_badges_$(git log -n1 | grep commit | cut -d ' ' -f 2)_$(date +%s)"
          #git checkout -b "${BRANCH}"

          EXIT_CODE=${{ steps.snyk.outcome }}
          echo "EXIT_CODE: ${EXIT_CODE}"
          if [ "$EXIT_CODE" == "success" ]; then
            go run cmd/tools/badge-maker/main.go -name "LINT" -status "passing" -color "green" 
          else
            go run cmd/tools/badge-maker/main.go -name "LINT" -status "failing" -color "red"
          fi
          git add badges/SNYK.svg
          git commit -m "update security badge" -a || {
             echo "No changes to commit"
             exit 0
          }
          git push origin "$(git branch --show-current)"
