---
name: main-branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run Linters and Security Scans
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
#          - 'arm64'
        go-opsys:
          - 'darwin'
#          - 'linux'
#          - 'windows'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run linter ${{ matrix.go-version }}
        shell: bash
        run: |
          PATH=$(go env GOPATH):${PATH} make security
