name: main-branch

on:
  push:
  pull_request:

jobs:
  security:
    name: Run Security Scan
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'darwin'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
