---
name: main-branch

on:
  push:
  pull_request:

jobs:
  security:
    name: Run Security Scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'darwin'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: go mod tidy
        shell: bash
        run: go mod tidy

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
