---
name: main-branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  security:
    name: Run Security Scan
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'darwin'
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
