---
name: main-branch

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  security:
    name: Run Security Scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'darwin'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: go mod tidy
        shell: bash
        run: go mod tidy

      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Setup Git
        shell: bash
        run: |
          git config --local user.email "github@samcaldwell.net"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: Generate Badge
        id: badge
        run: |
          EXIT_CODE=${{ steps.snyk.outcome }}
          echo "EXIT_CODE: ${{ steps.snyk.outcome }}"
          if [ "${{ steps.snyk.outcome }}" == "success" ]; then
            go run cmd/tools/badge-maker/main.go -name "SNYK" -status "passing" -color "green" 
          else
            go run cmd/tools/badge-maker/main.go -name "SNYK" -status "failing" -color "red"
          fi
          git add badges/SNYK.svg
          git commit -m "update security badge" -a || {
             echo "No changes to commit"
             exit 0
          }
          git push origin "$(git branch --show-current)"