---
name: workflow-01-lint

on:
  workflow_run:
    workflows:
      - "workflow-00-setup"
    types:
      - completed
  push:
  pull_request:
    branches:
      - main
jobs:
  debug:
    name: debug-step
    runs-on: ubuntu-latest
    needs:
      - config
    steps:
      - name: show config
        run: |
          echo "LINT_ENABLED: '${{ needs.config.outputs.lint-enabled }}'"
          echo "TEST_ENABLED: '${{ needs.config.outputs.test-enabled }}'"
          echo "BUILD_ENABLED: '${{ needs.config.outputs.build-enabled }}'"
  lint:
    name: Run the Linter
    needs:
      - config
    if: ${{ needs.config.outputs.lint-enabled }}
    runs-on: ubuntu-latest
    outputs:
      lint-successful: ${{ steps.lint-successful.outputs.success }}
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.20'
          - '1.19'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run linter ${{ matrix.go-version }}
        id: lint-successful
        run: |
            make lint

