---
name: workflow-00-setup

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  config:
    name: configure-pipeline
    runs-on: ubuntu-latest
    env:
      LINT_ENABLED: true   # Set this to 'true' to enable linting
      TEST_ENABLED: false   # Set this to 'true' to enable testing
      BUILD_ENABLED: true  # Set this to 'true' to enable building
    outputs:
      lint-enabled: ${{ env.LINT_ENABLED }} # pass to the next step
      test-enabled: ${{ env.TEST_ENABLED }} # pass to the next step
      build-enabled: ${{ env.BUILD_ENABLED }} # pass to the next step
    steps:
      - name: done
        id: done
        run: |
          echo "LINT_ENABLED: ${{ env.LINT_ENABLED }}"
          echo "TEST_ENABLED: ${{ env.TEST_ENABLED }}"
          echo "BUILD_ENABLED: ${{ env.BUILD_ENABLED }}"
  debug:
    name: debug-step
    runs-on: ubuntu-latest
    needs:
      - config
    steps:
      - name: show config
        run: |
          echo "LINT_ENABLED: '${{ needs.config.outputs.lint-enabled }}'"
          echo "TEST_ENABLED: '${{ needs.config.outputs.test-enabled }}'"
          echo "BUILD_ENABLED: '${{ needs.config.outputs.build-enabled }}'"

  lint:
    name: Run the Linter
    needs:
      - config
    if: ${{ needs.config.outputs.lint-enabled }}
    runs-on: ubuntu-latest
    outputs:
      lint-successful: ${{ steps.lint-successful.outputs.success }}
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.20'
          - '1.19'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run linter ${{ matrix.go-version }}
        id: lint-successful
        run: |
            make lint

  test:
    name: Run Tests
    needs:
      - config
      - lint
    if: ${{ needs.config.outputs.test-enabled }}
    runs-on: ubuntu-latest
    outputs:
      test-successful: ${{ steps.test-successful.outputs.success }}
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.20'
          - '1.19'
        go-arch: [ 'amd64', 'arm64' ]
        go-opsys: [ 'linux', 'darwin', 'windows' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests ${{ matrix.go-version }}
        id: test-successful
        run: |
          if [ "${{ needs.lint.outputs.lint-enabled }}" = "true" ]; then
            make test/simple
          else
            echo "Tests disabled"
          fi
