---
name: workflow-03-build

on:
  workflow_run:
    workflows:
     - "workflow-00-setup"
     - "workflow-01-lint"
     - "workflow-02-test"
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  noop:
    name: noop
    runs-on: ubuntu-latest
    steps:
      - name: useless-task
        run: echo "good enough to be government work...or AT&T"
  test:
    name: Run Builder
    needs: lint.outputs.test-successful
    runs-on: ubuntu-latest
    outputs:
      build-successful: ${{ steps.build-successful.outputs.success }}
    env:
      LINT_ENABLED: ${{ needs.config.outputs.lint-enabled }}   # Set this to 'true' to enable linting
      TEST_ENABLED: ${{ needs.config.outputs.test-enabled }}   # Set this to 'true' to enable testing
      BUILD_ENABLED: ${{ needs.config.outputs.build-enabled }}  # Set this to 'true' to enable building
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.20'
        go-arch: [ 'amd64' ]
        go-opsys: [ 'linux' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests ${{ matrix.go-version }}
        id: build-successful
        run: |
          if [ "${{ needs.configure.outputs.lint-enabled }}" = "true" ]; then
            make build
          else
            echo "Artifact Build disabled"
          fi
